version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
      nodejs: 22
    commands:
      - echo "Installing backend dependencies..."
      - cd backend
      - python -m pip install --upgrade pip
      - pip install -r requirements.txt
      - cd ..

      - echo "Installing frontend dependencies..."
      - cd frontend
      - npm install
      - cd ..

  build:
    commands:
      - echo "Building React application..."
      - cd frontend
      - npm run build
      - cd ..

      - echo "Checking FastAPI..."
      - cd backend
      - python -m compileall .
      - cd ..

artifacts:
  files:
    - '**/*'
